/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.rythmML;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RythmMLStandaloneSetup extends RythmMLStandaloneSetupGenerated {

	public static void doSetup() {
		new RythmMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
