/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.rythmML.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.rythmML.RythmMLRuntimeModule;
import org.xtext.example.rythmML.RythmMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RythmMLIdeSetup extends RythmMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RythmMLRuntimeModule(), new RythmMLIdeModule()));
	}
	
}
