/**
 * generated by Xtext
 */
package org.xtext.example.rythmML.serializer;

import org.xtext.example.rythmML.serializer.AbstractRythmMLSyntacticSequencer;

@SuppressWarnings("all")
public class RythmMLSyntacticSequencer extends AbstractRythmMLSyntacticSequencer {
}
