/**
 * generated by Xtext
 */
package org.xtext.example.rythmML.serializer;

import org.xtext.example.rythmML.serializer.AbstractRythmMLSemanticSequencer;

@SuppressWarnings("all")
public class RythmMLSemanticSequencer extends AbstractRythmMLSemanticSequencer {
}
