<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rythmML" nsURI="http://www.example.org/rythmML" nsPrefix="rythmML">
  <eClassifiers xsi:type="ecore:EClass" name="Song">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" lowerBound="1"
        upperBound="-1" eType="#//Track" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Track">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" lowerBound="1"
        upperBound="-1" eType="#//Sequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bars" lowerBound="1" upperBound="-1"
        eType="#//Bar" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beats" lowerBound="1" upperBound="-1"
        eType="#//Beat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Beat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ticks" lowerBound="1" upperBound="-1"
        eType="#//Tick" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tick"/>
  <eClassifiers xsi:type="ecore:EClass" name="Note">
    <eStructuralFeatures xsi:type="ecore:EReference" name="beat" lowerBound="1" eType="#//Beat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tick" lowerBound="1" eType="#//Tick"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bar" lowerBound="1" eType="#//Bar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass8" abstract="true"/>
</ecore:EPackage>
