/**
 * generated by Xtext
 */
package org.xtext.example.rythmML.ui.contentassist;

import org.xtext.example.rythmML.ui.contentassist.AbstractRythmMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RythmMLProposalProvider extends AbstractRythmMLProposalProvider {
}
