/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.rythmML.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RythmMLUiModule extends AbstractRythmMLUiModule {

	public RythmMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
