/*
 * generated by Xtext
 */
package org.xtext.example.rythmML.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.rythmML.services.RythmMLGrammarAccess;

public class RythmMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RythmMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.rythmML.parser.antlr.internal.InternalRythmMLParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.rythmML.parser.antlr.internal.InternalRythmMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Song";
	}
	
	public RythmMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RythmMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
